version: '3.4'

services:
  todoapi:
    image: ${DOCKER_REGISTRY}todoapi
    build:
      context: .
      dockerfile: todoapi/Dockerfile

  todoweb:
    image: ${DOCKER_REGISTRY}todoweb
    build:
      context: .
      dockerfile: todoweb/Dockerfile

