version: '3.4'

services:
  todoapi:
    image: todoapi
    build:
      context: .
      dockerfile: todoapi/Dockerfile

  todoweb:
    image: todoweb
    build:
      context: .
      dockerfile: todoweb/Dockerfile